import { HealthMonitorProcessor, ProcessorOptions } from './processor.types';
import { FrameData } from '../common/types';
export declare class ProcessorManager implements HealthMonitorProcessor {
    private readonly state;
    private readonly onFaceDetected;
    private readonly onImageData;
    private readonly onVitalSign;
    private readonly onFinalResults;
    private readonly onError;
    private readonly onWarning?;
    private readonly resolveFeatures;
    private readonly logAlgoMeasurements;
    private readonly doLogging;
    private readonly doPerformance;
    private readonly doRecording;
    private readonly doMeasuring;
    private readonly sdkLogger;
    private readonly rriLogger;
    private osType;
    private readonly logs;
    private measurementStartTime;
    private errorListener;
    private subjectDemographic;
    private orientation;
    private strictMeasurementGuidance;
    private lastImageWidth;
    private lastImageHeight;
    private readonly cameraId;
    private readonly licenseOptions;
    constructor({ onFaceDetected, onImageData, onVitalSign, onFinalResults, onError, onWarning, resolveFeatures, logAlgoMeasurements, doLogging, doPerformance, doRecording, doMeasuring, sdkLogger, rriLogger, requestedOrientation, subjectDemographic, strictMeasurementGuidance, cameraId, licenseOptions }: ProcessorOptions);
    init(): Promise<void>;
    private setReportListener;
    private setFaceListener;
    private setImageDataListener;
    setErrorListener: (onError: any) => void;
    private setMessageListener;
    private publishError;
    private publishWarning;
    private publishAlgoMessage;
    private hasFrameDimensionsChanged;
    private initEngine;
    close(): Promise<void>;
    process(frameData: FrameData, invalidOrientation: boolean): void;
    start(): void;
    stop(withReport: boolean): Promise<void>;
    private getMeasurementTime;
    private publishLogs;
}
